FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY AppData.sln .
COPY AppAPI/AppAPI.csproj AppAPI/
COPY AppData/AppData.csproj AppData/

RUN dotnet restore AppAPI/AppAPI.csproj

COPY AppAPI/ AppAPI/
COPY AppData/ AppData/

RUN dotnet publish AppAPI/AppAPI.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "AppAPI.dll"]
