FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY AppData.sln .
COPY AppView/AppView.csproj AppView/
COPY AppData/AppData.csproj AppData/

RUN dotnet restore AppView/AppView.csproj

COPY AppView/ AppView/
COPY AppData/ AppData/

RUN dotnet publish AppView/AppView.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "AppView.dll"]
