version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.Api
    ports:
      - "5000:80"
    networks:
      - appnetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  view:
    build:
      context: .
      dockerfile: Dockerfile.View
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - appnetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  appnetwork:
    driver: bridge